package constants

// System Configuration Constants
const (
	// Default Values
	DEFAULT_VITALITY            = 10
	DEFAULT_ENDURANCE           = 10
	DEFAULT_CONSTITUTION        = 10
	DEFAULT_INTELLIGENCE        = 10
	DEFAULT_WISDOM              = 10
	DEFAULT_CHARISMA            = 10
	DEFAULT_WILLPOWER           = 10
	DEFAULT_LUCK                = 10
	DEFAULT_FATE                = 10
	DEFAULT_KARMA               = 0
	DEFAULT_STRENGTH            = 10
	DEFAULT_AGILITY             = 10
	DEFAULT_PERSONALITY         = 10
	DEFAULT_SPIRITUAL_ENERGY    = 0
	DEFAULT_PHYSICAL_ENERGY     = 0
	DEFAULT_MENTAL_ENERGY       = 0
	DEFAULT_CULTIVATION_LEVEL   = 0
	DEFAULT_BREAKTHROUGH_POINTS = 0
	DEFAULT_LIFE_SPAN           = 100
	DEFAULT_AGE                 = 0

	// Min/Max Values
	MIN_STAT_VALUE          = 0
	MAX_STAT_VALUE          = 999999
	MIN_LEVEL               = 1
	MAX_LEVEL               = 1000
	MIN_CULTIVATION_LEVEL   = 0
	MAX_CULTIVATION_LEVEL   = 10000
	MIN_BREAKTHROUGH_POINTS = 0
	MAX_BREAKTHROUGH_POINTS = 1000000

	// Cache Configuration
	DEFAULT_CACHE_SIZE             = 1000
	DEFAULT_CACHE_TTL              = 300 // 5 minutes
	DEFAULT_CACHE_CLEANUP_INTERVAL = 60  // 1 minute

	// Performance Configuration
	DEFAULT_MAX_CONCURRENT_CALCULATIONS = 100
	DEFAULT_CALCULATION_TIMEOUT         = 5000               // 5 seconds
	DEFAULT_MEMORY_LIMIT                = 1024 * 1024 * 1024 // 1GB
	DEFAULT_CPU_LIMIT                   = 80                 // 80%

	// Database Configuration
	DEFAULT_DB_MAX_CONNECTIONS    = 100
	DEFAULT_DB_MIN_CONNECTIONS    = 10
	DEFAULT_DB_CONNECTION_TIMEOUT = 10 // 10 seconds
	DEFAULT_DB_QUERY_TIMEOUT      = 30 // 30 seconds

	// Security Configuration
	DEFAULT_PASSWORD_MIN_LENGTH = 8
	DEFAULT_PASSWORD_MAX_LENGTH = 128
	DEFAULT_MAX_LOGIN_ATTEMPTS  = 5
	DEFAULT_LOCKOUT_DURATION    = 900   // 15 minutes
	DEFAULT_SESSION_TIMEOUT     = 3600  // 1 hour
	DEFAULT_TOKEN_EXPIRY        = 86400 // 24 hours

	// Logging Configuration
	DEFAULT_LOG_LEVEL       = "info"
	DEFAULT_LOG_FORMAT      = "json"
	DEFAULT_LOG_MAX_SIZE    = 100 // 100MB
	DEFAULT_LOG_MAX_BACKUPS = 5
	DEFAULT_LOG_MAX_AGE     = 30 // 30 days

	// Monitoring Configuration
	DEFAULT_METRICS_ENABLED   = true
	DEFAULT_METRICS_PORT      = 9090
	DEFAULT_HEALTH_CHECK_PORT = 8081
	DEFAULT_PROFILING_ENABLED = false
	DEFAULT_PROFILING_PORT    = 6060

	// Flexible Systems Configuration
	DEFAULT_MAX_FLEXIBLE_STATS     = 1000
	DEFAULT_MAX_SPEED_TYPES        = 100
	DEFAULT_MAX_KARMA_TYPES        = 50
	DEFAULT_MAX_DIVISION_TYPES     = 20
	DEFAULT_MAX_PROFICIENCY_SKILLS = 500
	DEFAULT_MAX_SKILLS             = 1000

	// Formula Configuration
	DEFAULT_MAX_FORMULA_LENGTH = 10000
	DEFAULT_MAX_DEPENDENCIES   = 100
	DEFAULT_MAX_FORMULA_DEPTH  = 10
	DEFAULT_FORMULA_CACHE_SIZE = 5000

	// Validation Configuration
	DEFAULT_VALIDATION_TIMEOUT    = 5 // 5 seconds
	DEFAULT_MAX_VALIDATION_ERRORS = 100
	DEFAULT_STRICT_VALIDATION     = false

	// Hot Reload Configuration
	DEFAULT_HOT_RELOAD_ENABLED  = true
	DEFAULT_HOT_RELOAD_INTERVAL = 1  // 1 second
	DEFAULT_HOT_RELOAD_TIMEOUT  = 10 // 10 seconds

	// Backup Configuration
	DEFAULT_BACKUP_ENABLED     = true
	DEFAULT_BACKUP_INTERVAL    = 86400 // 24 hours
	DEFAULT_BACKUP_RETENTION   = 30    // 30 days
	DEFAULT_BACKUP_COMPRESSION = true

	// Rate Limiting Configuration
	DEFAULT_RATE_LIMIT_ENABLED  = true
	DEFAULT_RATE_LIMIT_REQUESTS = 1000 // per minute
	DEFAULT_RATE_LIMIT_WINDOW   = 60   // 1 minute
	DEFAULT_RATE_LIMIT_BURST    = 100

	// Encryption Configuration
	DEFAULT_ENCRYPTION_ALGORITHM  = "AES-256-GCM"
	DEFAULT_KEY_ROTATION_INTERVAL = 86400 * 7 // 7 days
	DEFAULT_ENCRYPTION_ENABLED    = true

	// Clustering Configuration
	DEFAULT_CLUSTER_ENABLED            = false
	DEFAULT_CLUSTER_NODES              = 1
	DEFAULT_CLUSTER_DISCOVERY_TIMEOUT  = 30 // 30 seconds
	DEFAULT_CLUSTER_HEARTBEAT_INTERVAL = 5  // 5 seconds
)

// Configuration Keys
const (
	CONFIG_APP_NAME        = "app.name"
	CONFIG_APP_VERSION     = "app.version"
	CONFIG_APP_ENVIRONMENT = "app.environment"
	CONFIG_APP_DEBUG       = "app.debug"

	CONFIG_SERVER_PORT        = "server.port"
	CONFIG_SERVER_HOST        = "server.host"
	CONFIG_SERVER_TIMEOUT     = "server.timeout"
	CONFIG_SERVER_TLS_ENABLED = "server.tls.enabled"

	CONFIG_DATABASE_URI             = "database.uri"
	CONFIG_DATABASE_NAME            = "database.name"
	CONFIG_DATABASE_TIMEOUT         = "database.timeout"
	CONFIG_DATABASE_MAX_CONNECTIONS = "database.max_connections"
	CONFIG_DATABASE_MIN_CONNECTIONS = "database.min_connections"

	CONFIG_CACHE_HOST     = "cache.host"
	CONFIG_CACHE_PORT     = "cache.port"
	CONFIG_CACHE_PASSWORD = "cache.password"
	CONFIG_CACHE_DB       = "cache.db"
	CONFIG_CACHE_TIMEOUT  = "cache.timeout"

	CONFIG_LOGGING_LEVEL            = "logging.level"
	CONFIG_LOGGING_FORMAT           = "logging.format"
	CONFIG_LOGGING_OUTPUT           = "logging.output"
	CONFIG_LOGGING_FILE_PATH        = "logging.file.path"
	CONFIG_LOGGING_FILE_MAX_SIZE    = "logging.file.max_size"
	CONFIG_LOGGING_FILE_MAX_BACKUPS = "logging.file.max_backups"
	CONFIG_LOGGING_FILE_MAX_AGE     = "logging.file.max_age"

	CONFIG_MONITORING_ENABLED   = "monitoring.enabled"
	CONFIG_MONITORING_PORT      = "monitoring.port"
	CONFIG_MONITORING_PATH      = "monitoring.path"
	CONFIG_HEALTH_CHECK_ENABLED = "health_check.enabled"
	CONFIG_HEALTH_CHECK_PORT    = "health_check.port"
	CONFIG_HEALTH_CHECK_PATH    = "health_check.path"

	CONFIG_SECURITY_JWT_SECRET           = "security.jwt.secret"
	CONFIG_SECURITY_JWT_EXPIRATION       = "security.jwt.expiration"
	CONFIG_SECURITY_RATE_LIMIT_ENABLED   = "security.rate_limit.enabled"
	CONFIG_SECURITY_RATE_LIMIT_REQUESTS  = "security.rate_limit.requests"
	CONFIG_SECURITY_RATE_LIMIT_WINDOW    = "security.rate_limit.window"
	CONFIG_SECURITY_ENCRYPTION_ENABLED   = "security.encryption.enabled"
	CONFIG_SECURITY_ENCRYPTION_ALGORITHM = "security.encryption.algorithm"
	CONFIG_SECURITY_ENCRYPTION_KEY       = "security.encryption.key"

	CONFIG_FLEXIBLE_SYSTEMS_ENABLED            = "flexible_systems.enabled"
	CONFIG_FLEXIBLE_SYSTEMS_MAX_STATS          = "flexible_systems.max_stats"
	CONFIG_FLEXIBLE_SYSTEMS_MAX_SPEED_TYPES    = "flexible_systems.max_speed_types"
	CONFIG_FLEXIBLE_SYSTEMS_MAX_KARMA_TYPES    = "flexible_systems.max_karma_types"
	CONFIG_FLEXIBLE_SYSTEMS_MAX_DIVISION_TYPES = "flexible_systems.max_division_types"

	CONFIG_FORMULA_MAX_LENGTH       = "formula.max_length"
	CONFIG_FORMULA_MAX_DEPENDENCIES = "formula.max_dependencies"
	CONFIG_FORMULA_MAX_DEPTH        = "formula.max_depth"
	CONFIG_FORMULA_CACHE_SIZE       = "formula.cache_size"

	CONFIG_VALIDATION_TIMEOUT    = "validation.timeout"
	CONFIG_VALIDATION_MAX_ERRORS = "validation.max_errors"
	CONFIG_VALIDATION_STRICT     = "validation.strict"

	CONFIG_HOT_RELOAD_ENABLED  = "hot_reload.enabled"
	CONFIG_HOT_RELOAD_INTERVAL = "hot_reload.interval"
	CONFIG_HOT_RELOAD_TIMEOUT  = "hot_reload.timeout"

	CONFIG_BACKUP_ENABLED     = "backup.enabled"
	CONFIG_BACKUP_INTERVAL    = "backup.interval"
	CONFIG_BACKUP_RETENTION   = "backup.retention"
	CONFIG_BACKUP_COMPRESSION = "backup.compression"

	CONFIG_CLUSTER_ENABLED            = "cluster.enabled"
	CONFIG_CLUSTER_NODES              = "cluster.nodes"
	CONFIG_CLUSTER_DISCOVERY_TIMEOUT  = "cluster.discovery_timeout"
	CONFIG_CLUSTER_HEARTBEAT_INTERVAL = "cluster.heartbeat_interval"
)

// Environment Variables
const (
	ENV_APP_NAME        = "ACTOR_CORE_APP_NAME"
	ENV_APP_VERSION     = "ACTOR_CORE_APP_VERSION"
	ENV_APP_ENVIRONMENT = "ACTOR_CORE_ENVIRONMENT"
	ENV_APP_DEBUG       = "ACTOR_CORE_DEBUG"

	ENV_SERVER_PORT    = "ACTOR_CORE_SERVER_PORT"
	ENV_SERVER_HOST    = "ACTOR_CORE_SERVER_HOST"
	ENV_SERVER_TIMEOUT = "ACTOR_CORE_SERVER_TIMEOUT"

	ENV_DATABASE_URI     = "ACTOR_CORE_DATABASE_URI"
	ENV_DATABASE_NAME    = "ACTOR_CORE_DATABASE_NAME"
	ENV_DATABASE_TIMEOUT = "ACTOR_CORE_DATABASE_TIMEOUT"

	ENV_CACHE_HOST     = "ACTOR_CORE_CACHE_HOST"
	ENV_CACHE_PORT     = "ACTOR_CORE_CACHE_PORT"
	ENV_CACHE_PASSWORD = "ACTOR_CORE_CACHE_PASSWORD"

	ENV_LOGGING_LEVEL  = "ACTOR_CORE_LOGGING_LEVEL"
	ENV_LOGGING_FORMAT = "ACTOR_CORE_LOGGING_FORMAT"
	ENV_LOGGING_OUTPUT = "ACTOR_CORE_LOGGING_OUTPUT"

	ENV_MONITORING_ENABLED = "ACTOR_CORE_MONITORING_ENABLED"
	ENV_MONITORING_PORT    = "ACTOR_CORE_MONITORING_PORT"

	ENV_SECURITY_JWT_SECRET     = "ACTOR_CORE_JWT_SECRET"
	ENV_SECURITY_ENCRYPTION_KEY = "ACTOR_CORE_ENCRYPTION_KEY"

	ENV_FLEXIBLE_SYSTEMS_ENABLED = "ACTOR_CORE_FLEXIBLE_SYSTEMS_ENABLED"

	ENV_HOT_RELOAD_ENABLED = "ACTOR_CORE_HOT_RELOAD_ENABLED"

	ENV_BACKUP_ENABLED = "ACTOR_CORE_BACKUP_ENABLED"

	ENV_CLUSTER_ENABLED = "ACTOR_CORE_CLUSTER_ENABLED"
)

// Default Configuration Values
var DefaultConfigValues = map[string]interface{}{
	CONFIG_APP_NAME:        "Actor Core v2.0",
	CONFIG_APP_VERSION:     "2.0.0",
	CONFIG_APP_ENVIRONMENT: "development",
	CONFIG_APP_DEBUG:       false,

	CONFIG_SERVER_PORT:        8080,
	CONFIG_SERVER_HOST:        "0.0.0.0",
	CONFIG_SERVER_TIMEOUT:     30,
	CONFIG_SERVER_TLS_ENABLED: false,

	CONFIG_DATABASE_URI:             "mongodb://localhost:27017",
	CONFIG_DATABASE_NAME:            "actor_core",
	CONFIG_DATABASE_TIMEOUT:         10,
	CONFIG_DATABASE_MAX_CONNECTIONS: 100,
	CONFIG_DATABASE_MIN_CONNECTIONS: 10,

	CONFIG_CACHE_HOST:     "localhost",
	CONFIG_CACHE_PORT:     6379,
	CONFIG_CACHE_PASSWORD: "",
	CONFIG_CACHE_DB:       0,
	CONFIG_CACHE_TIMEOUT:  5,

	CONFIG_LOGGING_LEVEL:            "info",
	CONFIG_LOGGING_FORMAT:           "json",
	CONFIG_LOGGING_OUTPUT:           "stdout",
	CONFIG_LOGGING_FILE_PATH:        "/var/log/actor-core",
	CONFIG_LOGGING_FILE_MAX_SIZE:    100,
	CONFIG_LOGGING_FILE_MAX_BACKUPS: 5,
	CONFIG_LOGGING_FILE_MAX_AGE:     30,

	CONFIG_MONITORING_ENABLED:   true,
	CONFIG_MONITORING_PORT:      9090,
	CONFIG_MONITORING_PATH:      "/metrics",
	CONFIG_HEALTH_CHECK_ENABLED: true,
	CONFIG_HEALTH_CHECK_PORT:    8081,
	CONFIG_HEALTH_CHECK_PATH:    "/health",

	CONFIG_SECURITY_JWT_SECRET:           "your-secret-key",
	CONFIG_SECURITY_JWT_EXPIRATION:       "24h",
	CONFIG_SECURITY_RATE_LIMIT_ENABLED:   true,
	CONFIG_SECURITY_RATE_LIMIT_REQUESTS:  1000,
	CONFIG_SECURITY_RATE_LIMIT_WINDOW:    60,
	CONFIG_SECURITY_ENCRYPTION_ENABLED:   true,
	CONFIG_SECURITY_ENCRYPTION_ALGORITHM: "AES-256-GCM",
	CONFIG_SECURITY_ENCRYPTION_KEY:       "your-encryption-key",

	CONFIG_FLEXIBLE_SYSTEMS_ENABLED:            true,
	CONFIG_FLEXIBLE_SYSTEMS_MAX_STATS:          1000,
	CONFIG_FLEXIBLE_SYSTEMS_MAX_SPEED_TYPES:    100,
	CONFIG_FLEXIBLE_SYSTEMS_MAX_KARMA_TYPES:    50,
	CONFIG_FLEXIBLE_SYSTEMS_MAX_DIVISION_TYPES: 20,

	CONFIG_FORMULA_MAX_LENGTH:       10000,
	CONFIG_FORMULA_MAX_DEPENDENCIES: 100,
	CONFIG_FORMULA_MAX_DEPTH:        10,
	CONFIG_FORMULA_CACHE_SIZE:       5000,

	CONFIG_VALIDATION_TIMEOUT:    5,
	CONFIG_VALIDATION_MAX_ERRORS: 100,
	CONFIG_VALIDATION_STRICT:     false,

	CONFIG_HOT_RELOAD_ENABLED:  true,
	CONFIG_HOT_RELOAD_INTERVAL: 1,
	CONFIG_HOT_RELOAD_TIMEOUT:  10,

	CONFIG_BACKUP_ENABLED:     true,
	CONFIG_BACKUP_INTERVAL:    86400,
	CONFIG_BACKUP_RETENTION:   30,
	CONFIG_BACKUP_COMPRESSION: true,

	CONFIG_CLUSTER_ENABLED:            false,
	CONFIG_CLUSTER_NODES:              1,
	CONFIG_CLUSTER_DISCOVERY_TIMEOUT:  30,
	CONFIG_CLUSTER_HEARTBEAT_INTERVAL: 5,
}
